;This AHK script converts any selected text from X-SAMPA to IPA using the table at https://en.wikipedia.org/wiki/X-SAMPA.
;To use, Install AHK from https://www.autohotkey.com, then run this AHK script
;Select any text in any text editor, press the hotkey to transform the text according to the X-SAMPA to IPA table
;Default hotkey is ALT+Q. Set hotkey in line 7 of this script. See https://www.autohotkey.com/docs/v2/howto/WriteHotkeys.htm for other modifiers.
;Visit NewDanishPhonetics at https://github.com/NewDanishPhonetics and https://www.patreon.com/NewDanishPhonetics -- ruben@schwa.dk

!q::

Clipboard := ""
SendInput, ^c
ClipWait 0
	
	Clipboard := StrReplace(Clipboard,"_R_F","᷈")
	Clipboard := StrReplace(Clipboard,"_B_L","᷅")
	Clipboard := StrReplace(Clipboard,"_H_T","᷄")
	Clipboard := StrReplace(Clipboard,"_x","̽")
	Clipboard := StrReplace(Clipboard,"_X","̆")
	Clipboard := StrReplace(Clipboard,"_w","ʷ")
	Clipboard := StrReplace(Clipboard,"_v","̬")
	Clipboard := StrReplace(Clipboard,"_t","̤")
	Clipboard := StrReplace(Clipboard,"_T","̋")
	Clipboard := StrReplace(Clipboard,"_r","̝")
	Clipboard := StrReplace(Clipboard,"_R","̌")
	Clipboard := StrReplace(Clipboard,"_q","̙")
	Clipboard := StrReplace(Clipboard,"_O","̹")
	Clipboard := StrReplace(Clipboard,"_o","̞")
	Clipboard := StrReplace(Clipboard,"_n","ⁿ")
	Clipboard := StrReplace(Clipboard,"_N","̼")
	Clipboard := StrReplace(Clipboard,"_m","̻")
	Clipboard := StrReplace(Clipboard,"_M","̄")
	Clipboard := StrReplace(Clipboard,"_l","ˡ")
	Clipboard := StrReplace(Clipboard,"_L","̀")
	Clipboard := StrReplace(Clipboard,"_k","̰")
	Clipboard := StrReplace(Clipboard,"_j","ʲ")
	Clipboard := StrReplace(Clipboard,"_h","ʰ")
	Clipboard := StrReplace(Clipboard,"_H","́")
	Clipboard := StrReplace(Clipboard,"_G","ˠ")
	Clipboard := StrReplace(Clipboard,"_F","̂")
	Clipboard := StrReplace(Clipboard,"_e","̴")
	Clipboard := StrReplace(Clipboard,"_d","̪")
	Clipboard := StrReplace(Clipboard,"_c","̜")
	Clipboard := StrReplace(Clipboard,"_B","̏")
	Clipboard := StrReplace(Clipboard,"_A","̘")
	Clipboard := StrReplace(Clipboard,"_a","̺")
	Clipboard := StrReplace(Clipboard,"_0","̥")
	Clipboard := StrReplace(Clipboard,"_~","̃")
	Clipboard := StrReplace(Clipboard,"_>","ʼ")
	Clipboard := StrReplace(Clipboard,"_=","̩")
	Clipboard := StrReplace(Clipboard,"_+","̟")
	Clipboard := StrReplace(Clipboard,"_^","̯")
	Clipboard := StrReplace(Clipboard,"_\","̂")
	Clipboard := StrReplace(Clipboard,"_/","̌")
	Clipboard := StrReplace(Clipboard,"_}","̚")
	Clipboard := StrReplace(Clipboard,"_","")
	Clipboard := StrReplace(Clipboard,"_?\","ˤ")
	Clipboard := StrReplace(Clipboard,"_-","̠")
	Clipboard := StrReplace(Clipboard,"<R>","↗")
	Clipboard := StrReplace(Clipboard,"<F>","↘")
	Clipboard := StrReplace(Clipboard,"z``","ʐ")
	Clipboard := StrReplace(Clipboard,"z\","ʑ")
	Clipboard := StrReplace(Clipboard,"Z","ʒ")
	Clipboard := StrReplace(Clipboard,"Y","ʏ")
	Clipboard := StrReplace(Clipboard,"x\","ɧ")
	Clipboard := StrReplace(Clipboard,"X\","ħ")
	Clipboard := StrReplace(Clipboard,"X","χ")
	Clipboard := StrReplace(Clipboard,"W","ʍ")
	Clipboard := StrReplace(Clipboard,"v\","ʋ")
	Clipboard := StrReplace(Clipboard,"V","ʌ")
	Clipboard := StrReplace(Clipboard,"U\","ʊ̈")
	Clipboard := StrReplace(Clipboard,"U","ʊ")
	Clipboard := StrReplace(Clipboard,"t``","ʈ")
	Clipboard := StrReplace(Clipboard,"T","θ")
	Clipboard := StrReplace(Clipboard,"s``","ʂ")
	Clipboard := StrReplace(Clipboard,"s\","ɕ")
	Clipboard := StrReplace(Clipboard,"S","ʃ")
	Clipboard := StrReplace(Clipboard,"r``","ɽ")
	Clipboard := StrReplace(Clipboard,"r\``","ɻ")
	Clipboard := StrReplace(Clipboard,"r\","ɹ")
	Clipboard := StrReplace(Clipboard,"R\","ʀ")
	Clipboard := StrReplace(Clipboard,"R","ʁ")
	Clipboard := StrReplace(Clipboard,"Q","ɒ")
	Clipboard := StrReplace(Clipboard,"p\","ɸ")
	Clipboard := StrReplace(Clipboard,"P","ʋ")
	Clipboard := StrReplace(Clipboard,"O\","ʘ")
	Clipboard := StrReplace(Clipboard,"O","ɔ")
	Clipboard := StrReplace(Clipboard,"n``","ɳ")
	Clipboard := StrReplace(Clipboard,"N\","ɴ")
	Clipboard := StrReplace(Clipboard,"N","ŋ")
	Clipboard := StrReplace(Clipboard,"M\","ɰ")
	Clipboard := StrReplace(Clipboard,"M","ɯ")
	Clipboard := StrReplace(Clipboard,"l`","ɭ")
	Clipboard := StrReplace(Clipboard,"l\","ɺ")
	Clipboard := StrReplace(Clipboard,"L\","ʟ")
	Clipboard := StrReplace(Clipboard,"L","ʎ")
	Clipboard := StrReplace(Clipboard,"K\","ɮ")
	Clipboard := StrReplace(Clipboard,"K","ɬ")
	Clipboard := StrReplace(Clipboard,"j\","ʝ")
	Clipboard := StrReplace(Clipboard,"J\_<","ʄ")
	Clipboard := StrReplace(Clipboard,"J\","ɟ")
	Clipboard := StrReplace(Clipboard,"J","ɲ")
	Clipboard := StrReplace(Clipboard,"I\","ɪ̈")
	Clipboard := StrReplace(Clipboard,"I","ɪ")
	Clipboard := StrReplace(Clipboard,"h\","ɦ")
	Clipboard := StrReplace(Clipboard,"H\","ʜ")
	Clipboard := StrReplace(Clipboard,"H","ɥ")
	Clipboard := StrReplace(Clipboard,"G\_<","ʛ")
	Clipboard := StrReplace(Clipboard,"G\","ɢ")
	Clipboard := StrReplace(Clipboard,"G","ɣ")
	Clipboard := StrReplace(Clipboard,"g_<","ɠ")
	Clipboard := StrReplace(Clipboard,"F","ɱ")
	Clipboard := StrReplace(Clipboard,"E","ɛ")
	Clipboard := StrReplace(Clipboard,"D","ð")
	Clipboard := StrReplace(Clipboard,"d_<","ɗ")
	Clipboard := StrReplace(Clipboard,"C","ç")
	Clipboard := StrReplace(Clipboard,"B\","ʙ")
	Clipboard := StrReplace(Clipboard,"B","β")
	Clipboard := StrReplace(Clipboard,"b_<","ɓ")
	Clipboard := StrReplace(Clipboard,"A","ɑ")
	Clipboard := StrReplace(Clipboard,"9","œ")
	Clipboard := StrReplace(Clipboard,"8","ɵ")
	Clipboard := StrReplace(Clipboard,"7","ɤ")
	Clipboard := StrReplace(Clipboard,"6","ɐ")
	Clipboard := StrReplace(Clipboard,"5","ɫ")
	Clipboard := StrReplace(Clipboard,"4","ɾ")
	Clipboard := StrReplace(Clipboard,"3\","ɞ")
	Clipboard := StrReplace(Clipboard,"3","ɜ")
	Clipboard := StrReplace(Clipboard,"2","ø")
	Clipboard := StrReplace(Clipboard,"1","ɨ")
	Clipboard := StrReplace(Clipboard,"~","̃")
	Clipboard := StrReplace(Clipboard,"||","‖")
	Clipboard := StrReplace(Clipboard,"|\|\","ǁ")
	Clipboard := StrReplace(Clipboard,"|\","ǀ")
	Clipboard := StrReplace(Clipboard,"|","|")
	Clipboard := StrReplace(Clipboard,">\","ʡ")
	Clipboard := StrReplace(Clipboard,"=","̩")
	Clipboard := StrReplace(Clipboard,"<\","ʢ")
	Clipboard := StrReplace(Clipboard,"^","ꜛ")
	Clipboard := StrReplace(Clipboard,"``","˞")
	Clipboard := StrReplace(Clipboard,"&","ɶ")
	Clipboard := StrReplace(Clipboard,"@\","ɘ")
	Clipboard := StrReplace(Clipboard,"@","ə")
	Clipboard := StrReplace(Clipboard,"}}}","͈")
	Clipboard := StrReplace(Clipboard,"}","ʉ")
	Clipboard := StrReplace(Clipboard,"{","æ")
	Clipboard := StrReplace(Clipboard,"'","ʲ")
	Clipboard := StrReplace(Clipboard,"?\","ʕ")
	Clipboard := StrReplace(Clipboard,"?","ʔ")
	Clipboard := StrReplace(Clipboard,"!\","ǃ")
	Clipboard := StrReplace(Clipboard,"!","ꜜ")
	Clipboard := StrReplace(Clipboard,":\","ˑ")
	Clipboard := StrReplace(Clipboard,":","ː")
	Clipboard := StrReplace(Clipboard,"-\","‿")
	Clipboard := StrReplace(Clipboard,"%","ˌ")


SendInput, ^v
Return
